In [4]:
import ndjson
import pandas as pd

In [5]:
with open("../../../../output_data/scraped_data/scraped_data_2023-03-10_0-1000000.ndjson") as f:
    d = ndjson.load(f)

In [6]:
len(d)

52555

In [35]:
x = [(_["id"], _["text"]) for _ in d if _["level"] == "0"]
len(x)

1666

In [52]:
a = pd.DataFrame(x)
a["len"] = a[1].str.len()
a = a.drop_duplicates(subset=[1])
a = a.reset_index(drop=True)
a

             0                                                  1   len
0     01125149  Web Server's Default Page\nWeb Server's Defaul...   772
1     05008656  Lunchroom Blocks Zwolle - Lunchen in Hartje Ce...  1375
2     01071763  Koerier Friesland - Spoedkoerier Speedcargo Ko...  1800
3     04064715  M & D Holland te Emmen\nM&D Holland is een pro...   718
4     08034622                            is functioning normally    23
...        ...                                                ...   ...
1558  82833176  Webshop | Fit For Fertility\nAlle producten\nO...  6562
1559  82832811  sloten-vervangen.nl\nhome\nover ons\ncilinders...  3558
1560  82668043  de verbouwmeesters\nMeteen naar de inhoud\nHom...  1638
1561  82993998  Uncle Sam’s Burgers – Best Burgers in Town.\nS...  3794
1562  82843724  Ronde Venen – Thuiszorg\nHit enter to search o...   989

[1563 rows x 3 columns]

In [84]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


vectorizer = TfidfVectorizer(max_df=0.05, min_df=0.001)
tfidf_matrix = vectorizer.fit_transform(a[1])
print(tfidf_matrix.shape)

# Calculate cosine similarity between all pairs of websites
similarity_matrix = cosine_similarity(tfidf_matrix)

(1563, 21917)

In [85]:
import numpy as np

labeled_dataset = []
for i in range(len(a)):
    # If the website has at least one other website with a similarity above the threshold,
    # label it as automatically generated content (1), otherwise label it as original content (0).
    similar_websites = np.where(similarity_matrix[i] >= 0.8)[0]
    label = 1 if len(similar_websites) > 1 else 0
    labeled_dataset.append((label, len(similar_websites)))

In [86]:
a["label"], a["sim_sites"] = zip(*labeled_dataset)
a

,0,1,len,label,sim_sites
0,01125149,Web Server's Default Page\nWeb Server's Defaul...,772,1,2
1,05008656,Lunchroom Blocks Zwolle - Lunchen in Hartje Ce...,1375,0,1
2,01071763,Koerier Friesland - Spoedkoerier Speedcargo Ko...,1800,0,1
3,04064715,M & D Holland te Emmen\nM&D Holland is een pro...,718,0,1
4,08034622,is functioning normally,23,1,2
...,...,...,...,...,...
1558,82833176,Webshop | Fit For Fertility\nAlle producten\nO...,6562,0,1
1559,82832811,sloten-vervangen.nl\nhome\nover ons\ncilinders...,3558,0,1
1560,82668043,de verbouwmeesters\nMeteen naar de inhoud\nHom...,1638,0,1
1561,82993998,Uncle Sam’s Burgers – Best Burgers in Town.\nS...,3794,0,1
1562,82843724,Ronde Venen – Thuiszorg\nHit enter to search o...,989,0,1

In [70]:
np.where(similarity_matrix[125] >= 0.7)[0]

array([125, 393])

In [60]:
a.loc[393, 1]

"VDL Zekerheid\nMenu\nHome\nOver ons\nWie zijn wij\nWat doen wij\nOnze dienstverlening\nOnze kwaliteitswaarborgen\nLinks\nParticulier\nPensioen\nHypotheek\nSparen\nKrediet\nFinancial planning\nUitvaart\nZorg\nWonen\nRecht\nVerkeer\nRecreatie\nLinks\nZakelijk\nOndernemer\nWerknemerspensioen\nEmployee benefits\nRisico analyse\nVerzekeringen\nLinks\nNieuwe situatie\nUw gezin\nSamenwonen en trouwen\nKinderen\nScheiden\nOverlijden\nUw werk en inkomen\nNieuwe baan\nPromotie\nOntslag\nZiek zijn\nArbeidsongeschikt raken\nEerder stoppen met werken\nMet pensioen gaan\nEigen zaak starten\nBelasting betalen\nUw woning\nHuis kopen\nHuis huren\nVerbouwen\nVerhuizen\nJe studie\nStudiefinanciering\nStudieschuld\nOp kamers gaan\nEchtscheiding\nKlantenservice\nPremie berekenen\nOfferte aanvragen\nWijzigingen doorgeven\nHandige rekentools\nSchade melden\nAdreswijziging\nBel-mij-service\nTotaalrelatie-service\nKlanttevredenheid\nAanbeveling\nKlachtmelding\nDownloads\nNieuws\nParticulier\nZakelijk\nAanmelden E-newsletter\nArchief E-newsletter\nRSS Feeds\nContact\nEerlijk, helder en onafhankelijk advies?\nMaak een vrijblijvende afspraak en bekijk de mogelijkheden\nParticuliere verzekeringen\nWe luisteren naar u: wat is uw gezins\xadsituatie, wat zijn uw wensen voor de toe\xadkomst, welke risico's kunt of wilt u zelf dragen en welke wilt u af\xaddekken?\nLees meer\nZakelijke verzekeringen\nWe begeleiden u bij risico analyse en risicobeheersing binnen uw onderneming en nemen u daarbij zoveel mogelijk werk uit handen.\nLees meer\nEchtscheiding\nScheiden is een stress\xadvolle en ingrijpende gebeurtenis. Het is een fase waarin uw veel emoties zult herkennen en waarin veel geregeld moet worden.\nLees meer\nHypotheken\nHeeft u een weloverwogen en onafhankelijk hypotheekadvies nodig? Dan bent u bij ons aan het goede adres.\nLees meer\nWijzigingen doorgeven\nSchade melden\nDownloads\nNieuws\nHypotheekrente blijft oplopen\nRente verder omhoog, banken concurreren om spaarders\nBelastingaangifte doen kan geld opleveren\nHuizenprijs in januari onverwachts omhoog\nNieuwsoverzicht\nWij zijn uw financieel advieskantoor\nAls financieel adviseur staan wij garant voor een deskundig, onafhankelijk advies in begrijpelijke taal. Zo'n advies geven wij u graag in een persoonlijk gesprek. Maar als uw gids en uw vraagbaak in een financiële wereld die steeds complexer wordt, willen wij u ook via onze website informeren en bieden wij u interessante feiten en actueel nieuws.\nOf u uw zaken nu via onze site wilt regelen of liever persoonlijk met ons bespreekt, wij zijn u graag van dienst!\nLees meer over ons\nKerkbuurt 52\n(ingang is aan de Gantelweg 20)\n3361 BJ Sliedrecht\n/\nT:\n0184 - 480 160\nE: info@vdlzekerheid.nl\nOns kantoor is geopend van\nmaandag t/m vrijdag van\n08.30 uur tot 17.00 uur\nKvk nummer 24328757| WFT nummer 12003108|\nDisclaimer\n|\nPrivacy\nWebsite by DenK Internet Solutions\nHome\nOver ons\nWie zijn wij\nWat doen wij\nOnze dienstverlening\nOnze kwaliteitswaarborgen\nLinks\nParticulier\nPensioen\nHypotheek\nSparen\nKrediet\nFinancial planning\nUitvaart\nZorg\nWonen\nRecht\nVerkeer\nRecreatie\nLinks\nZakelijk\nOndernemer\nWerknemerspensioen\nEmployee benefits\nRisico analyse\nVerzekeringen\nLinks\nNieuwe situatie\nUw gezin\nSamenwonen en trouwen\nKinderen\nScheiden\nOverlijden\nUw werk en inkomen\nNieuwe baan\nPromotie\nOntslag\nZiek zijn\nArbeidsongeschikt raken\nEerder stoppen met werken\nMet pensioen gaan\nEigen zaak starten\nBelasting betalen\nUw woning\nHuis kopen\nHuis huren\nVerbouwen\nVerhuizen\nJe studie\nStudiefinanciering\nStudieschuld\nOp kamers gaan\nEchtscheiding\nKlantenservice\nPremie berekenen\nOfferte aanvragen\nWijzigingen doorgeven\nHandige rekentools\nSchade melden\nAdreswijziging\nBel-mij-service\nTotaalrelatie-service\nKlanttevredenheid\nAanbeveling\nKlachtmelding\nDownloads\nNieuws\nParticulier\nZakelijk\nAanmelden E-newsletter\nArchief E-newsletter\nRSS Feeds\nContact\nOnze website plaatst\ngeen\ntracking cookies. Geïntegreerde (social) media als Facebook, YouTube of AddThis kunnen bij gebruik ervan dat wel doen.\nWat zijn cookies?\nEen cookie is een klein tekstbestand dat door een website op uw apparaat (computer, tablet of mobiele telefoon) wordt geplaatst.\nHoe wij cookies gebruiken\nWij plaatsen uitsluitend functionele cookies voor een optimale werking van de website. Bij uw volgende bezoek worden de cookies gebruikt om u te herkennen en dat maakt een volgend bezoek aan onze website gemakkelijker.\nCookies van derden\nBij de cookies die via onze website worden geplaatst, kunnen cookies van andere partijen zitten. Deze cookies meten bijvoorbeeld het gebruik van onze website. Deze zogenaamde statistische cookies geven ons inzichten waarmee wij onze website vervolgens verder kunnen optimaliseren om zo de gebruikerservaring van bezoekers te verbeteren. Deze inzichten gebruiken wij uitsluitend ten behoeve van onszelf en er worden geen gegevens gedeeld met derden zoals bijvoorbeeld Google.\nVerder treft u buttons aan van bijvoorbeeld Addthis, Facebook, Twitter of LinkedIn. Met deze buttons kunt u informatie van onze website delen. Ook is het mogelijk dat er video's van YouTube op onze website staan of applicaties van andere partijen. Hiervoor worden cookies geplaatst vanuit deze (social) media. Wij hebben daar geen invloed op. Wilt u hier meer over weten? Lees dan de privacyverklaringen van deze (social media)kanalen. Daarin staat wat zij met de (persoons)gegevens doen die zij via dit soort cookies verwerken.\nUitschakelen cookies\nU kunt het gebruik van cookies uitschakelen. Let erop dat u de instellingen apart voor elke browser en apparaat dat u gebruikt moet aanpassen. Hoe u uw instellingen kunt aanpassen, verschilt per browser. Raadpleeg hiervoor de handleiding van uw browser.\nWees u ervan bewust dat als u geen cookies wilt, wij niet meer kunnen garanderen dat onze website helemaal goed werkt. Het kan zijn dat enkele functies van de site verloren gaan.\nSlotopmerkingen\nWij zullen deze verklaring af en toe aan moeten passen, omdat bijvoorbeeld onze website of de regels rondom cookies wijzigen.\nTop\nOnze website maakt gebruik van JavaScript. U ziet deze melding alleen op het moment dat uw browser geen JavaScript ondersteunt of wanneer u JavaScript heeft uitgeschakeld."

In [87]:
a.loc[a["label"]==1]

,0,1,len,label,sim_sites
0,01125149,Web Server's Default Page\nWeb Server's Defaul...,772,1,2
4,08034622,is functioning normally,23,1,2
7,01142382,Apache is functioning normally,30,1,2
8,01182889,Secured Home of steenzetterijligthart.nl\nWelc...,149,1,12
122,09089448,Web Server's Default Page\nWeb Server's Defaul...,771,1,2
231,17078601,Op deze domeinnaam is nog geen website geconfi...,108,1,2
240,17131051,jumbodelaak.nl\njumbodelaak.nl\nSomething amaz...,196,1,2
254,17165888,Secured Home of e-scoop.com\nWelcome to e-scoo...,123,1,12
320,20099204,Secured Home of primos.eu\nWelcome to primos.e...,119,1,11
325,20131739,Secured Home of loodet.nl\nWelcome to loodet.n...,119,1,12
333,20162944,"ReShopDirect, Koop slim, wyze, wyze cam v3, wy...",2738,1,2
334,20134725,Secured Home of moerland-engineering.nl\nWelco...,147,1,11
457,28031843,Secured Home of zomerzorg.nl\nWelcome to zomer...,125,1,12
492,30099232,Domeinnaam Assuplus.nl overnemen? Doe een open...,5468,1,2
609,34226434,Secured Home of bouwbedrijfwerkhoven.nl\nWelco...,147,1,12
756,54021804,Homepage | Birch\nThema’s\nCases\nActueel\nDie...,4610,1,2
815,57585148,Secured Home of heinoswoodmill.nl\nWelcome to ...,135,1,12
816,57524610,Suspended Domain\nThis account has been suspen...,134,1,2
821,57960666,Suspended Domain\nThis account has been suspen...,124,1,2
922,61106356,ETB Nederland | Elektro Technisch Bureau\nHome...,5096,1,2
925,61704997,Secured Home of destinyflowers.nl\nWelcome to ...,135,1,12
1004,63935864,Secured Home of cleam4u.nl\nWelcome to cleam4u...,121,1,12
1027,64748170,Secured Home of 2xuu.nl\nWelcome to 2xuu.nl\nT...,115,1,12
1079,66484308,Auto Theorie Oefenen via SnelSlagen.nl\nGa naa...,6582,1,2
1101,67459773,"Coolmix - Refurbished iPhones, MacBooks en iPa...",2895,1,2
1295,73052809,rambostijl.nl\nrambostijl.nl\nSomething amazin...,194,1,2
1352,75500531,Sloopbedrijf Lelystad | DUIS Sloopwerken\nHome...,15908,1,2
1357,75554127,Secured Home of coopersandsmith.nl\nWelcome to...,137,1,12
1363,75730871,Zeilschip | De Amazone\nnl\nen\nHome\nMaritime...,16122,1,2
1465,80009360,Theorie oefenen op Wegrijden.nl - Probeer de t...,11352,1,2

In [31]:
np.where(similarity_matrix[1] >= 0.9)[0]

array([ 1, 81])